# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formatparamsdlg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_formatparamsdlg(object):
    def setupUi(self, formatparamsdlg):
        formatparamsdlg.setObjectName("formatparamsdlg")
        formatparamsdlg.resize(400, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(formatparamsdlg.sizePolicy().hasHeightForWidth())
        formatparamsdlg.setSizePolicy(sizePolicy)
        formatparamsdlg.setMinimumSize(QtCore.QSize(400, 650))
        formatparamsdlg.setMaximumSize(QtCore.QSize(400, 650))
        self.verticalLayout = QtWidgets.QVBoxLayout(formatparamsdlg)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fomatTitle = QtWidgets.QLabel(formatparamsdlg)
        self.fomatTitle.setObjectName("fomatTitle")
        self.horizontalLayout_2.addWidget(self.fomatTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(formatparamsdlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMinimumSize(QtCore.QSize(20, 20))
        self.closeButton.setMaximumSize(QtCore.QSize(20, 20))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(formatparamsdlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.crsNameCBox = QtWidgets.QCheckBox(self.frame)
        self.crsNameCBox.setChecked(True)
        self.crsNameCBox.setObjectName("crsNameCBox")
        self.horizontalLayout_4.addWidget(self.crsNameCBox)
        # self.crsNameLineEdit = QtWidgets.QLineEdit(self.frame)
        # self.crsNameLineEdit.setObjectName("crsNameLineEdit")
        # self.horizontalLayout_4.addWidget(self.crsNameLineEdit)
        self.crsNameLineEdit = QtWidgets.QComboBox(self.frame)
        self.crsNameLineEdit.setObjectName("crsNameLineEdit")
        self.horizontalLayout_4.addWidget(self.crsNameLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_42.setSpacing(5)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.accCBox = QtWidgets.QCheckBox(self.frame)
        self.accCBox.setChecked(True)
        self.accCBox.setObjectName("accCBox")
        self.horizontalLayout_42.addWidget(self.accCBox)
        self.accLineEdit = QtWidgets.QComboBox(self.frame)
        self.accLineEdit.setObjectName("accLineEdit")
        self.horizontalLayout_42.addWidget(self.accLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_42)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        # self.xResCBox = QtWidgets.QLineEdit(self.frame)
        # self.xResCBox.setChecked(True)
        # self.xResCBox.setObjectName("xResCBox")

        self.xResCBox = QtWidgets.QLabel(self.frame)
        self.xResCBox.setAlignment(QtCore.Qt.AlignCenter)
        self.xResCBox.setObjectName("xResCBox")
        self.horizontalLayout_5.addWidget(self.xResCBox)

        self.xResLineEdit = QtWidgets.QLineEdit(self.frame)
        self.xResLineEdit.setObjectName("xResLineEdit")
        self.horizontalLayout_5.addWidget(self.xResLineEdit)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.xResLineEdit2 = QtWidgets.QLineEdit(self.frame)
        self.xResLineEdit2.setObjectName("xResLineEdit2")
        self.horizontalLayout_5.addWidget(self.xResLineEdit2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)


        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        # self.yResCBox = QtWidgets.QCheckBox(self.frame)
        # self.yResCBox.setChecked(True)
        # self.yResCBox.setObjectName("yResCBox")
        self.yResCBox = QtWidgets.QLabel(self.frame)
        self.yResCBox.setAlignment(QtCore.Qt.AlignCenter)
        self.yResCBox.setObjectName("yResCBox")
        self.horizontalLayout_52.addWidget(self.yResCBox)
        self.yResLineEdit = QtWidgets.QLineEdit(self.frame)
        self.yResLineEdit.setObjectName("yResLineEdit")
        self.horizontalLayout_52.addWidget(self.yResLineEdit)
        self.line2 = QtWidgets.QFrame(self.frame)
        self.line2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.horizontalLayout_52.addWidget(self.line2)
        self.yResLineEdit2 = QtWidgets.QLineEdit(self.frame)
        self.yResLineEdit2.setObjectName("yResLineEdit2")
        self.horizontalLayout_52.addWidget(self.yResLineEdit2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_52)


        self.groupBox = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.datumNameCBox = QtWidgets.QCheckBox(self.groupBox)
        self.datumNameCBox.setChecked(True)
        self.datumNameCBox.setObjectName("datumNameCBox")
        self.horizontalLayout.addWidget(self.datumNameCBox)
        self.datumNameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datumNameLineEdit.sizePolicy().hasHeightForWidth())
        self.datumNameLineEdit.setSizePolicy(sizePolicy)
        self.datumNameLineEdit.setObjectName("datumNameLineEdit")
        self.horizontalLayout.addWidget(self.datumNameLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.spNameCBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.spNameCBox.setChecked(True)
        self.spNameCBox.setObjectName("spNameCBox")
        self.gridLayout.addWidget(self.spNameCBox, 0, 0, 1, 1)
        self.ieLineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.ieLineEdit.setObjectName("ieLineEdit")
        self.gridLayout.addWidget(self.ieLineEdit, 2, 1, 1, 1)
        self.smajorLineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.smajorLineEdit.setObjectName("smajorLineEdit")
        self.gridLayout.addWidget(self.smajorLineEdit, 1, 1, 1, 1)
        self.spNameLineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.spNameLineEdit.setObjectName("spNameLineEdit")
        self.gridLayout.addWidget(self.spNameLineEdit, 0, 1, 1, 1)
        self.smajorCBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.smajorCBox.setChecked(True)
        self.smajorCBox.setObjectName("smajorCBox")
        self.gridLayout.addWidget(self.smajorCBox, 1, 0, 1, 1)
        self.ieCBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.ieCBox.setChecked(True)
        self.ieCBox.setObjectName("ieCBox")
        self.gridLayout.addWidget(self.ieCBox, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.unitNameCBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.unitNameCBox.setChecked(True)
        self.unitNameCBox.setObjectName("unitNameCBox")
        self.gridLayout_2.addWidget(self.unitNameCBox, 0, 0, 1, 1)
        self.unitNameLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.unitNameLineEdit.setObjectName("unitNameLineEdit")
        self.gridLayout_2.addWidget(self.unitNameLineEdit, 0, 1, 1, 1)
        self.unitrpuLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.unitrpuLineEdit.setObjectName("unitrpuLineEdit")
        self.gridLayout_2.addWidget(self.unitrpuLineEdit, 3, 1, 1, 1)
        self.unitrpuCBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.unitrpuCBox.setChecked(True)
        self.unitrpuCBox.setObjectName("unitrpuCBox")
        self.gridLayout_2.addWidget(self.unitrpuCBox, 3, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.primemNameCBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.primemNameCBox.setChecked(True)
        self.primemNameCBox.setObjectName("primemNameCBox")
        self.gridLayout_3.addWidget(self.primemNameCBox, 0, 0, 1, 1)
        self.primemlonCBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.primemlonCBox.setChecked(True)
        self.primemlonCBox.setObjectName("primemlonCBox")
        self.gridLayout_3.addWidget(self.primemlonCBox, 1, 0, 1, 1)
        self.primemNameLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.primemNameLineEdit.setObjectName("primemNameLineEdit")
        self.gridLayout_3.addWidget(self.primemNameLineEdit, 0, 1, 1, 1)
        self.primemlonLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.primemlonLineEdit.setObjectName("primemlonLineEdit")
        self.gridLayout_3.addWidget(self.primemlonLineEdit, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.cancelButton = QtWidgets.QPushButton(formatparamsdlg)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        self.okButton = QtWidgets.QPushButton(formatparamsdlg)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_3.addWidget(self.okButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.retranslateUi(formatparamsdlg)
        QtCore.QMetaObject.connectSlotsByName(formatparamsdlg)

        self.crsNameLineEdit.currentIndexChanged.connect(self.crsNameCurrentIndexChanged)
        self.accLineEdit.currentIndexChanged.connect(self.accCurrentIndexChanged)

        self.initConfig()


    def crsNameCurrentIndexChanged(self):
        self.accLineEdit.clear()
        [self.accLineEdit.addItem(x) for x in self.jsonDict[self.crsNameLineEdit.currentText()]['分辨率集合']]
        self.datumNameLineEdit.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['基准面名称'])
        self.spNameLineEdit.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['椭球体名称'])
        self.ieLineEdit.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['椭球体反扁率'])
        self.smajorLineEdit.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['椭球体长半轴'])
        self.unitNameLineEdit.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['角度单位名称'])
        self.unitrpuLineEdit.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['每单位弧度'])
        self.primemNameLineEdit.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['本初子午线名称'])
        self.primemlonLineEdit.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['本初子午线经度'])

    def accCurrentIndexChanged(self):
        if self.accLineEdit.currentText() == '':
            # clear
            return
        self.xResLineEdit.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['分辨率集合'][self.accLineEdit.currentText()]['x'][0].__str__())
        self.xResLineEdit2.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['分辨率集合'][self.accLineEdit.currentText()]['x'][1].__str__())
        self.yResLineEdit.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['分辨率集合'][self.accLineEdit.currentText()]['y'][0].__str__())
        self.yResLineEdit2.setText(self.jsonDict[self.crsNameLineEdit.currentText()]['分辨率集合'][self.accLineEdit.currentText()]['y'][1].__str__())


    def initConfig(self):
        import json
        jsonname = '分辨率与坐标系检查参数表.json'
        self.jsonDict = {}
        with open(jsonname, 'r', encoding='utf-8') as f:
            self.jsonDict = json.load(f)

        if self.jsonDict.__len__() != 0:
            for item in self.jsonDict:
                self.crsNameLineEdit.addItem(item.__str__())
            for item in self.jsonDict:
                # [self.accLineEdit.addItem(x.__str__()) for x in self.jsonDict[item]['分辨率集合']]
                self.xResLineEdit.setText(self.jsonDict[item]['分辨率集合'][self.accLineEdit.currentText()]['x'][0].__str__())
                self.xResLineEdit2.setText(self.jsonDict[item]['分辨率集合'][self.accLineEdit.currentText()]['x'][1].__str__())
                self.yResLineEdit.setText(self.jsonDict[item]['分辨率集合'][self.accLineEdit.currentText()]['y'][0].__str__())
                self.yResLineEdit2.setText(self.jsonDict[item]['分辨率集合'][self.accLineEdit.currentText()]['y'][1].__str__())
                self.datumNameLineEdit.setText(self.jsonDict[item]['基准面名称'])
                self.spNameLineEdit.setText(self.jsonDict[item]['椭球体名称'])
                self.ieLineEdit.setText(self.jsonDict[item]['椭球体反扁率'])
                self.smajorLineEdit.setText(self.jsonDict[item]['椭球体长半轴'])
                self.unitNameLineEdit.setText(self.jsonDict[item]['角度单位名称'])
                self.unitrpuLineEdit.setText(self.jsonDict[item]['每单位弧度'])
                self.primemNameLineEdit.setText(self.jsonDict[item]['本初子午线名称'])
                self.primemlonLineEdit.setText(self.jsonDict[item]['本初子午线经度'])
                break

    def retranslateUi(self, formatparamsdlg):
        _translate = QtCore.QCoreApplication.translate
        formatparamsdlg.setWindowTitle(_translate("formatparamsdlg", "Dialog"))
        self.fomatTitle.setText(_translate("formatparamsdlg", "参数设置"))
        self.closeButton.setText(_translate("formatparamsdlg", "×"))
        self.crsNameCBox.setText(_translate("formatparamsdlg", "坐标系名称："))
        self.accCBox.setText(_translate("formatparamsdlg", "分辨率（米）："))
        # self.crsNameLineEdit.setText(_translate("formatparamsdlg", "GCS_China_Geodetic_Coordinate_System_2000"))
        self.xResCBox.setText(_translate("formatparamsdlg", "X分辨率范围："))
        self.xResLineEdit.setText(_translate("formatparamsdlg", "0.00001"))
        self.xResLineEdit2.setText(_translate("formatparamsdlg", "0.00001"))
        self.yResCBox.setText(_translate("formatparamsdlg", "Y分辨率范围："))
        self.yResLineEdit.setText(_translate("formatparamsdlg", "0.00001"))
        self.yResLineEdit2.setText(_translate("formatparamsdlg", "0.00001"))
        self.groupBox.setTitle(_translate("formatparamsdlg", "基准面(DATUM)"))
        self.datumNameCBox.setText(_translate("formatparamsdlg", "名称："))
        self.datumNameLineEdit.setText(_translate("formatparamsdlg", "D_China_2000"))
        self.groupBox_4.setTitle(_translate("formatparamsdlg", "椭球体(SPHEROID)"))
        self.spNameCBox.setText(_translate("formatparamsdlg", "名称："))
        self.ieLineEdit.setText(_translate("formatparamsdlg", "298.257222101"))
        self.smajorLineEdit.setText(_translate("formatparamsdlg", "6378137.0"))
        self.spNameLineEdit.setText(_translate("formatparamsdlg", "CGCS2000"))
        self.smajorCBox.setText(_translate("formatparamsdlg", "长半轴："))
        self.ieCBox.setText(_translate("formatparamsdlg", "反扁率："))
        self.groupBox_2.setTitle(_translate("formatparamsdlg", "角度单位(UNIT)"))
        self.unitNameCBox.setText(_translate("formatparamsdlg", "名称："))
        self.unitNameLineEdit.setText(_translate("formatparamsdlg", "Degree"))
        self.unitrpuLineEdit.setText(_translate("formatparamsdlg", "0.017453292519943295"))
        self.unitrpuCBox.setText(_translate("formatparamsdlg", "每单位弧度："))
        self.groupBox_3.setTitle(_translate("formatparamsdlg", "本初子午线(PRIMEM)"))
        self.primemNameCBox.setText(_translate("formatparamsdlg", "名称："))
        self.primemlonCBox.setText(_translate("formatparamsdlg", "经度："))
        self.primemNameLineEdit.setText(_translate("formatparamsdlg", "Greenwich"))
        self.primemlonLineEdit.setText(_translate("formatparamsdlg", "0.0"))
        self.cancelButton.setText(_translate("formatparamsdlg", "取消"))
        self.okButton.setText(_translate("formatparamsdlg", "确定"))

