# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(5000, 5000))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainHLayout = QtWidgets.QHBoxLayout()
        self.mainHLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.mainHLayout.setContentsMargins(5, 5, 5, 5)
        self.mainHLayout.setSpacing(5)
        self.mainHLayout.setObjectName("mainHLayout")
        self.modelScrollArea = QtWidgets.QScrollArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelScrollArea.sizePolicy().hasHeightForWidth())
        self.modelScrollArea.setSizePolicy(sizePolicy)
        self.modelScrollArea.setMinimumSize(QtCore.QSize(210, 0))
        self.modelScrollArea.setMaximumSize(QtCore.QSize(210, 16777215))
        self.modelScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.modelScrollArea.setWidgetResizable(True)
        self.modelScrollArea.setObjectName("modelScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 191, 521))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.modelVerticalLayout = QtWidgets.QVBoxLayout()
        self.modelVerticalLayout.setContentsMargins(11, 11, 11, 11)
        self.modelVerticalLayout.setSpacing(2)
        self.modelVerticalLayout.setObjectName("modelVerticalLayout")
        self.domButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.domButton.setMinimumSize(QtCore.QSize(0, 80))
        self.domButton.setMaximumSize(QtCore.QSize(16777215, 80))
        self.domButton.setObjectName("domButton")
        self.modelVerticalLayout.addWidget(self.domButton)
        self.demButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.demButton.setMinimumSize(QtCore.QSize(0, 80))
        self.demButton.setMaximumSize(QtCore.QSize(16777215, 80))
        self.demButton.setObjectName("demButton")
        self.modelVerticalLayout.addWidget(self.demButton)
        self.stdataButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.stdataButton.setMinimumSize(QtCore.QSize(0, 80))
        self.stdataButton.setMaximumSize(QtCore.QSize(16777215, 80))
        self.stdataButton.setObjectName("stdataButton")
        self.modelVerticalLayout.addWidget(self.stdataButton)
        self.modelButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.modelButton.setMinimumSize(QtCore.QSize(0, 80))
        self.modelButton.setMaximumSize(QtCore.QSize(16777215, 80))
        self.modelButton.setObjectName("modelButton")
        self.modelVerticalLayout.addWidget(self.modelButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.modelVerticalLayout.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.modelVerticalLayout)
        self.modelScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainHLayout.addWidget(self.modelScrollArea)
        self.mainContent = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainContent.sizePolicy().hasHeightForWidth())
        self.mainContent.setSizePolicy(sizePolicy)
        self.mainContent.setTabBarAutoHide(False)
        self.mainContent.setObjectName("mainContent")
        self.domContentTab = QtWidgets.QWidget()
        self.domContentTab.setObjectName("domContentTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.domContentTab)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.domVLayout = QtWidgets.QVBoxLayout()
        self.domVLayout.setContentsMargins(5, 5, 5, 5)
        self.domVLayout.setSpacing(5)
        self.domVLayout.setObjectName("domVLayout")
        self.domContent = QtWidgets.QTabWidget(self.domContentTab)
        self.domContent.setObjectName("domContent")
        self.domWBTab = QtWidgets.QWidget()
        self.domWBTab.setObjectName("domWBTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.domWBTab)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.domWBVLayout = QtWidgets.QVBoxLayout()
        self.domWBVLayout.setContentsMargins(5, 5, 5, 5)
        self.domWBVLayout.setSpacing(5)
        self.domWBVLayout.setObjectName("domWBVLayout")
        self.domWBParamsVLayout = QtWidgets.QVBoxLayout()
        self.domWBParamsVLayout.setContentsMargins(5, 5, 5, 5)
        self.domWBParamsVLayout.setSpacing(5)
        self.domWBParamsVLayout.setObjectName("domWBParamsVLayout")
        self.domWBParamsIGLayout = QtWidgets.QGridLayout()
        self.domWBParamsIGLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.domWBParamsIGLayout.setContentsMargins(5, 5, 5, 5)
        self.domWBParamsIGLayout.setSpacing(5)
        self.domWBParamsIGLayout.setObjectName("domWBParamsIGLayout")
        self.domWBILabel = QtWidgets.QLabel(self.domWBTab)
        self.domWBILabel.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBILabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBILabel.setObjectName("domWBILabel")
        self.domWBParamsIGLayout.addWidget(self.domWBILabel, 0, 0, 1, 1)
        self.domWBIBrowerButton = QtWidgets.QPushButton(self.domWBTab)
        self.domWBIBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBIBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBIBrowerButton.setObjectName("domWBIBrowerButton")
        self.domWBParamsIGLayout.addWidget(self.domWBIBrowerButton, 0, 2, 1, 1)
        self.domWBILineEdit = QtWidgets.QLineEdit(self.domWBTab)
        self.domWBILineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBILineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBILineEdit.setObjectName("domWBILineEdit")
        self.domWBParamsIGLayout.addWidget(self.domWBILineEdit, 0, 1, 1, 1)
        self.domWBParamsVLayout.addLayout(self.domWBParamsIGLayout)
        self.domWBParamsGBox = QtWidgets.QGroupBox(self.domWBTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domWBParamsGBox.sizePolicy().hasHeightForWidth())
        self.domWBParamsGBox.setSizePolicy(sizePolicy)
        self.domWBParamsGBox.setMinimumSize(QtCore.QSize(0, 80))
        self.domWBParamsGBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.domWBParamsGBox.setObjectName("domWBParamsGBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.domWBParamsGBox)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.domWBParamsGBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.domWBParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox.setMaximum(255)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.domWBParamsGBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.domWBParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout.addWidget(self.spinBox_2)
        self.label_3 = QtWidgets.QLabel(self.domWBParamsGBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox_3 = QtWidgets.QSpinBox(self.domWBParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_3.sizePolicy().hasHeightForWidth())
        self.spinBox_3.setSizePolicy(sizePolicy)
        self.spinBox_3.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox_3.setMaximum(9999)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout.addWidget(self.spinBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.domWBParamsVLayout.addWidget(self.domWBParamsGBox)
        self.domWBPraramsOGLayout = QtWidgets.QGridLayout()
        self.domWBPraramsOGLayout.setContentsMargins(5, 5, 5, 5)
        self.domWBPraramsOGLayout.setSpacing(5)
        self.domWBPraramsOGLayout.setObjectName("domWBPraramsOGLayout")
        self.domWBOLabel = QtWidgets.QLabel(self.domWBTab)
        self.domWBOLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBOLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBOLabel.setObjectName("domWBOLabel")
        self.domWBPraramsOGLayout.addWidget(self.domWBOLabel, 0, 0, 1, 1)
        self.domWBOLineEdit = QtWidgets.QLineEdit(self.domWBTab)
        self.domWBOLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBOLineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBOLineEdit.setObjectName("domWBOLineEdit")
        self.domWBPraramsOGLayout.addWidget(self.domWBOLineEdit, 0, 1, 1, 1)
        self.domWBOBrowerButton = QtWidgets.QPushButton(self.domWBTab)
        self.domWBOBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBOBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBOBrowerButton.setObjectName("domWBOBrowerButton")
        self.domWBPraramsOGLayout.addWidget(self.domWBOBrowerButton, 0, 2, 1, 1)
        self.domWBParamsVLayout.addLayout(self.domWBPraramsOGLayout)
        self.line = QtWidgets.QFrame(self.domWBTab)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.domWBParamsVLayout.addWidget(self.line)
        self.domWBOpHLayout = QtWidgets.QHBoxLayout()
        self.domWBOpHLayout.setContentsMargins(5, 5, 5, 5)
        self.domWBOpHLayout.setSpacing(5)
        self.domWBOpHLayout.setObjectName("domWBOpHLayout")
        self.domWBReportButton = QtWidgets.QPushButton(self.domWBTab)
        self.domWBReportButton.setObjectName("domWBReportButton")
        self.domWBOpHLayout.addWidget(self.domWBReportButton)
        self.domWBLogButton = QtWidgets.QPushButton(self.domWBTab)
        self.domWBLogButton.setObjectName("domWBLogButton")
        self.domWBOpHLayout.addWidget(self.domWBLogButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.domWBOpHLayout.addItem(spacerItem2)
        self.domWBStartButton = QtWidgets.QPushButton(self.domWBTab)
        self.domWBStartButton.setObjectName("domWBStartButton")
        self.domWBOpHLayout.addWidget(self.domWBStartButton)
        self.domWBParamsVLayout.addLayout(self.domWBOpHLayout)
        self.domWBVLayout.addLayout(self.domWBParamsVLayout)
        self.domTableView = QtWidgets.QTableView(self.domWBTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domTableView.sizePolicy().hasHeightForWidth())
        self.domTableView.setSizePolicy(sizePolicy)
        self.domTableView.setObjectName("domTableView")
        self.domWBVLayout.addWidget(self.domTableView)
        self.verticalLayout_3.addLayout(self.domWBVLayout)
        self.domContent.addTab(self.domWBTab, "")
        self.domCoverTab = QtWidgets.QWidget()
        self.domCoverTab.setObjectName("domCoverTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.domCoverTab)
        self.verticalLayout_8.setContentsMargins(11, 5, 5, 5)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.domCVLayout = QtWidgets.QVBoxLayout()
        self.domCVLayout.setContentsMargins(5, 5, 5, 5)
        self.domCVLayout.setSpacing(5)
        self.domCVLayout.setObjectName("domCVLayout")
        self.domCParamsVLayout = QtWidgets.QVBoxLayout()
        self.domCParamsVLayout.setContentsMargins(5, 5, 5, 5)
        self.domCParamsVLayout.setSpacing(5)
        self.domCParamsVLayout.setObjectName("domCParamsVLayout")
        self.domCParamsIGLayout = QtWidgets.QGridLayout()
        self.domCParamsIGLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.domCParamsIGLayout.setContentsMargins(5, 5, 5, 5)
        self.domCParamsIGLayout.setSpacing(5)
        self.domCParamsIGLayout.setObjectName("domCParamsIGLayout")
        self.domCILabel = QtWidgets.QLabel(self.domCoverTab)
        self.domCILabel.setMinimumSize(QtCore.QSize(0, 24))
        self.domCILabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domCILabel.setObjectName("domCILabel")
        self.domCParamsIGLayout.addWidget(self.domCILabel, 0, 0, 1, 1)
        self.domCIBrowerButton = QtWidgets.QPushButton(self.domCoverTab)
        self.domCIBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domCIBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domCIBrowerButton.setObjectName("domCIBrowerButton")
        self.domCParamsIGLayout.addWidget(self.domCIBrowerButton, 0, 2, 1, 1)
        self.domCILineEdit = QtWidgets.QLineEdit(self.domCoverTab)
        self.domCILineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domCILineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domCILineEdit.setObjectName("domCILineEdit")
        self.domCParamsIGLayout.addWidget(self.domCILineEdit, 0, 1, 1, 1)
        self.domCParamsVLayout.addLayout(self.domCParamsIGLayout)
        self.domCParamsADGLayout = QtWidgets.QGridLayout()
        self.domCParamsADGLayout.setContentsMargins(5, 5, 5, 5)
        self.domCParamsADGLayout.setSpacing(5)
        self.domCParamsADGLayout.setObjectName("domCParamsADGLayout")
        self.domCADLabel = QtWidgets.QLabel(self.domCoverTab)
        self.domCADLabel.setObjectName("domCADLabel")
        self.domCParamsADGLayout.addWidget(self.domCADLabel, 0, 0, 1, 1)
        self.domCADLineEdit = QtWidgets.QLineEdit(self.domCoverTab)
        self.domCADLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domCADLineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domCADLineEdit.setObjectName("domCADLineEdit")
        self.domCParamsADGLayout.addWidget(self.domCADLineEdit, 0, 1, 1, 1)
        self.domCADBrowerButton = QtWidgets.QPushButton(self.domCoverTab)
        self.domCADBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domCADBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domCADBrowerButton.setObjectName("domCADBrowerButton")
        self.domCParamsADGLayout.addWidget(self.domCADBrowerButton, 0, 2, 1, 1)
        self.domCParamsVLayout.addLayout(self.domCParamsADGLayout)
        self.domCParamsGBox = QtWidgets.QGroupBox(self.domCoverTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domCParamsGBox.sizePolicy().hasHeightForWidth())
        self.domCParamsGBox.setSizePolicy(sizePolicy)
        self.domCParamsGBox.setMinimumSize(QtCore.QSize(0, 80))
        self.domCParamsGBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.domCParamsGBox.setObjectName("domCParamsGBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.domCParamsGBox)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.domCParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.comCCityComboBox = QtWidgets.QComboBox(self.domCParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comCCityComboBox.sizePolicy().hasHeightForWidth())
        self.comCCityComboBox.setSizePolicy(sizePolicy)
        self.comCCityComboBox.setObjectName("comCCityComboBox")
        self.horizontalLayout_5.addWidget(self.comCCityComboBox)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.domCParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.domCCountyComboBox = QtWidgets.QComboBox(self.domCParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domCCountyComboBox.sizePolicy().hasHeightForWidth())
        self.domCCountyComboBox.setSizePolicy(sizePolicy)
        self.domCCountyComboBox.setObjectName("domCCountyComboBox")
        self.horizontalLayout_4.addWidget(self.domCCountyComboBox)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.domCParamsVLayout.addWidget(self.domCParamsGBox)
        self.domCPraramsOGLayout = QtWidgets.QGridLayout()
        self.domCPraramsOGLayout.setContentsMargins(5, 5, 5, 5)
        self.domCPraramsOGLayout.setSpacing(5)
        self.domCPraramsOGLayout.setObjectName("domCPraramsOGLayout")
        self.domCOLabel = QtWidgets.QLabel(self.domCoverTab)
        self.domCOLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.domCOLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domCOLabel.setObjectName("domCOLabel")
        self.domCPraramsOGLayout.addWidget(self.domCOLabel, 0, 0, 1, 1)
        self.domCOLineEdit = QtWidgets.QLineEdit(self.domCoverTab)
        self.domCOLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domCOLineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domCOLineEdit.setObjectName("domCOLineEdit")
        self.domCPraramsOGLayout.addWidget(self.domCOLineEdit, 0, 1, 1, 1)
        self.domCOBrowerButton = QtWidgets.QPushButton(self.domCoverTab)
        self.domCOBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domCOBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domCOBrowerButton.setObjectName("domCOBrowerButton")
        self.domCPraramsOGLayout.addWidget(self.domCOBrowerButton, 0, 2, 1, 1)
        self.domCParamsVLayout.addLayout(self.domCPraramsOGLayout)
        self.line_2 = QtWidgets.QFrame(self.domCoverTab)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.domCParamsVLayout.addWidget(self.line_2)
        self.domCOpHLayout = QtWidgets.QHBoxLayout()
        self.domCOpHLayout.setContentsMargins(5, 5, 5, 5)
        self.domCOpHLayout.setSpacing(5)
        self.domCOpHLayout.setObjectName("domCOpHLayout")
        self.domCReportButton = QtWidgets.QPushButton(self.domCoverTab)
        self.domCReportButton.setObjectName("domCReportButton")
        self.domCOpHLayout.addWidget(self.domCReportButton)
        self.domCLogButton = QtWidgets.QPushButton(self.domCoverTab)
        self.domCLogButton.setObjectName("domCLogButton")
        self.domCOpHLayout.addWidget(self.domCLogButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.domCOpHLayout.addItem(spacerItem3)
        self.domCStartButton = QtWidgets.QPushButton(self.domCoverTab)
        self.domCStartButton.setObjectName("domCStartButton")
        self.domCOpHLayout.addWidget(self.domCStartButton)
        self.domCParamsVLayout.addLayout(self.domCOpHLayout)
        self.domCVLayout.addLayout(self.domCParamsVLayout)
        self.domCTableWidget = QtWidgets.QTableWidget(self.domCoverTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domCTableWidget.sizePolicy().hasHeightForWidth())
        self.domCTableWidget.setSizePolicy(sizePolicy)
        self.domCTableWidget.setObjectName("domCTableWidget")
        self.domCTableWidget.setColumnCount(0)
        self.domCTableWidget.setRowCount(0)
        self.domCVLayout.addWidget(self.domCTableWidget)
        self.verticalLayout_8.addLayout(self.domCVLayout)
        self.domContent.addTab(self.domCoverTab, "")
        self.domFormatTab = QtWidgets.QWidget()
        self.domFormatTab.setObjectName("domFormatTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.domFormatTab)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.domFormatVLayout = QtWidgets.QVBoxLayout()
        self.domFormatVLayout.setContentsMargins(5, 5, 5, 5)
        self.domFormatVLayout.setSpacing(5)
        self.domFormatVLayout.setObjectName("domFormatVLayout")
        self.domFormatParamsVLayout = QtWidgets.QVBoxLayout()
        self.domFormatParamsVLayout.setContentsMargins(5, 5, 5, 5)
        self.domFormatParamsVLayout.setSpacing(5)
        self.domFormatParamsVLayout.setObjectName("domFormatParamsVLayout")
        self.domFormatParamsIGLayout = QtWidgets.QGridLayout()
        self.domFormatParamsIGLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.domFormatParamsIGLayout.setContentsMargins(5, 5, 5, 5)
        self.domFormatParamsIGLayout.setSpacing(5)
        self.domFormatParamsIGLayout.setObjectName("domFormatParamsIGLayout")
        self.domFormatILabel = QtWidgets.QLabel(self.domFormatTab)
        self.domFormatILabel.setMinimumSize(QtCore.QSize(0, 24))
        self.domFormatILabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domFormatILabel.setObjectName("domFormatILabel")
        self.domFormatParamsIGLayout.addWidget(self.domFormatILabel, 0, 0, 1, 1)
        self.domFormatIBrowerButton = QtWidgets.QPushButton(self.domFormatTab)
        self.domFormatIBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domFormatIBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domFormatIBrowerButton.setObjectName("domFormatIBrowerButton")
        self.domFormatParamsIGLayout.addWidget(self.domFormatIBrowerButton, 0, 2, 1, 1)
        self.domFormatILineEdit = QtWidgets.QLineEdit(self.domFormatTab)
        self.domFormatILineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domFormatILineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domFormatILineEdit.setObjectName("domFormatILineEdit")
        self.domFormatParamsIGLayout.addWidget(self.domFormatILineEdit, 0, 1, 1, 1)
        self.domFormatParamsVLayout.addLayout(self.domFormatParamsIGLayout)
        self.domFormatParamsGBox = QtWidgets.QGroupBox(self.domFormatTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domFormatParamsGBox.sizePolicy().hasHeightForWidth())
        self.domFormatParamsGBox.setSizePolicy(sizePolicy)
        self.domFormatParamsGBox.setMinimumSize(QtCore.QSize(0, 80))
        self.domFormatParamsGBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.domFormatParamsGBox.setObjectName("domFormatParamsGBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.domFormatParamsGBox)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.domFormatListWidget = QtWidgets.QListWidget(self.domFormatParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domFormatListWidget.sizePolicy().hasHeightForWidth())
        self.domFormatListWidget.setSizePolicy(sizePolicy)
        self.domFormatListWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.domFormatListWidget.setObjectName("domFormatListWidget")
        self.verticalLayout_4.addWidget(self.domFormatListWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.domFormatPButtonVLayout = QtWidgets.QVBoxLayout()
        self.domFormatPButtonVLayout.setContentsMargins(5, 5, 5, 5)
        self.domFormatPButtonVLayout.setSpacing(5)
        self.domFormatPButtonVLayout.setObjectName("domFormatPButtonVLayout")
        self.domFormatPSettingButton = QtWidgets.QPushButton(self.domFormatParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domFormatPSettingButton.sizePolicy().hasHeightForWidth())
        self.domFormatPSettingButton.setSizePolicy(sizePolicy)
        self.domFormatPSettingButton.setObjectName("domFormatPSettingButton")
        self.domFormatPButtonVLayout.addWidget(self.domFormatPSettingButton)
        self.domFormatPResetButton = QtWidgets.QPushButton(self.domFormatParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domFormatPResetButton.sizePolicy().hasHeightForWidth())
        self.domFormatPResetButton.setSizePolicy(sizePolicy)
        self.domFormatPResetButton.setObjectName("domFormatPResetButton")
        self.domFormatPButtonVLayout.addWidget(self.domFormatPResetButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.domFormatPButtonVLayout.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.domFormatPButtonVLayout)
        self.domFormatParamsVLayout.addWidget(self.domFormatParamsGBox)
        self.line_4 = QtWidgets.QFrame(self.domFormatTab)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.domFormatParamsVLayout.addWidget(self.line_4)
        self.domFormatOpHLayout = QtWidgets.QHBoxLayout()
        self.domFormatOpHLayout.setContentsMargins(5, 5, 5, 5)
        self.domFormatOpHLayout.setSpacing(5)
        self.domFormatOpHLayout.setObjectName("domFormatOpHLayout")
        self.domFormatReportButton = QtWidgets.QPushButton(self.domFormatTab)
        self.domFormatReportButton.setObjectName("domFormatReportButton")
        self.domFormatOpHLayout.addWidget(self.domFormatReportButton)
        self.domFormatLogButton = QtWidgets.QPushButton(self.domFormatTab)
        self.domFormatLogButton.setObjectName("domFormatLogButton")
        self.domFormatOpHLayout.addWidget(self.domFormatLogButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.domFormatOpHLayout.addItem(spacerItem5)
        self.domFormatStartButton = QtWidgets.QPushButton(self.domFormatTab)
        self.domFormatStartButton.setObjectName("domFormatStartButton")
        self.domFormatOpHLayout.addWidget(self.domFormatStartButton)
        self.domFormatParamsVLayout.addLayout(self.domFormatOpHLayout)
        self.domFormatVLayout.addLayout(self.domFormatParamsVLayout)
        self.domFormatTableWidget = QtWidgets.QTableWidget(self.domFormatTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domFormatTableWidget.sizePolicy().hasHeightForWidth())
        self.domFormatTableWidget.setSizePolicy(sizePolicy)
        self.domFormatTableWidget.setObjectName("domFormatTableWidget")
        self.domFormatTableWidget.setColumnCount(0)
        self.domFormatTableWidget.setRowCount(0)
        self.domFormatVLayout.addWidget(self.domFormatTableWidget)
        self.verticalLayout_6.addLayout(self.domFormatVLayout)
        self.domContent.addTab(self.domFormatTab, "")
        self.domMatchTab = QtWidgets.QWidget()
        self.domMatchTab.setObjectName("domMatchTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.domMatchTab)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.domMatchVLayout = QtWidgets.QVBoxLayout()
        self.domMatchVLayout.setContentsMargins(5, 5, 5, 5)
        self.domMatchVLayout.setSpacing(5)
        self.domMatchVLayout.setObjectName("domMatchVLayout")
        self.domMatchParamsVLayout = QtWidgets.QVBoxLayout()
        self.domMatchParamsVLayout.setContentsMargins(5, 5, 5, 5)
        self.domMatchParamsVLayout.setSpacing(5)
        self.domMatchParamsVLayout.setObjectName("domMatchParamsVLayout")
        self.domMatchParamsIndexGLayout = QtWidgets.QGridLayout()
        self.domMatchParamsIndexGLayout.setContentsMargins(5, 5, 5, 5)
        self.domMatchParamsIndexGLayout.setSpacing(5)
        self.domMatchParamsIndexGLayout.setObjectName("domMatchParamsIndexGLayout")
        self.domMatchIndexLabel = QtWidgets.QLabel(self.domMatchTab)
        self.domMatchIndexLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.domMatchIndexLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domMatchIndexLabel.setObjectName("domMatchIndexLabel")
        self.domMatchParamsIndexGLayout.addWidget(self.domMatchIndexLabel, 0, 0, 1, 1)
        self.domMatchIndexBrowerButton = QtWidgets.QPushButton(self.domMatchTab)
        self.domMatchIndexBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domMatchIndexBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domMatchIndexBrowerButton.setObjectName("domMatchIndexBrowerButton")
        self.domMatchParamsIndexGLayout.addWidget(self.domMatchIndexBrowerButton, 0, 2, 1, 1)
        self.domMatchIndexLineEdit = QtWidgets.QLineEdit(self.domMatchTab)
        self.domMatchIndexLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domMatchIndexLineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domMatchIndexLineEdit.setObjectName("domMatchIndexLineEdit")
        self.domMatchParamsIndexGLayout.addWidget(self.domMatchIndexLineEdit, 0, 1, 1, 1)
        self.domMatchParamsVLayout.addLayout(self.domMatchParamsIndexGLayout)
        self.line_6 = QtWidgets.QFrame(self.domMatchTab)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.domMatchParamsVLayout.addWidget(self.line_6)
        self.domMatchOpHLayout = QtWidgets.QHBoxLayout()
        self.domMatchOpHLayout.setContentsMargins(5, 5, 5, 5)
        self.domMatchOpHLayout.setSpacing(5)
        self.domMatchOpHLayout.setObjectName("domMatchOpHLayout")
        self.domMatchReportButton = QtWidgets.QPushButton(self.domMatchTab)
        self.domMatchReportButton.setObjectName("domMatchReportButton")
        self.domMatchOpHLayout.addWidget(self.domMatchReportButton)
        self.domMatchLogButton = QtWidgets.QPushButton(self.domMatchTab)
        self.domMatchLogButton.setObjectName("domMatchLogButton")
        self.domMatchOpHLayout.addWidget(self.domMatchLogButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.domMatchOpHLayout.addItem(spacerItem6)
        self.domMatchStartButton = QtWidgets.QPushButton(self.domMatchTab)
        self.domMatchStartButton.setObjectName("domMatchStartButton")
        self.domMatchOpHLayout.addWidget(self.domMatchStartButton)
        self.domMatchParamsVLayout.addLayout(self.domMatchOpHLayout)
        self.domMatchVLayout.addLayout(self.domMatchParamsVLayout)
        self.domMatchTableWidget = QtWidgets.QTableWidget(self.domMatchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domMatchTableWidget.sizePolicy().hasHeightForWidth())
        self.domMatchTableWidget.setSizePolicy(sizePolicy)
        self.domMatchTableWidget.setObjectName("domMatchTableWidget")
        self.domMatchTableWidget.setColumnCount(0)
        self.domMatchTableWidget.setRowCount(0)
        self.domMatchVLayout.addWidget(self.domMatchTableWidget)
        self.verticalLayout_7.addLayout(self.domMatchVLayout)
        self.domContent.addTab(self.domMatchTab, "")
        self.domVLayout.addWidget(self.domContent)
        self.verticalLayout_2.addLayout(self.domVLayout)
        self.mainContent.addTab(self.domContentTab, "")
        self.demContentTab = QtWidgets.QWidget()
        self.demContentTab.setObjectName("demContentTab")
        self.mainContent.addTab(self.demContentTab, "")
        self.stdataContentTab = QtWidgets.QWidget()
        self.stdataContentTab.setObjectName("stdataContentTab")
        self.mainContent.addTab(self.stdataContentTab, "")
        self.modelContentTab = QtWidgets.QWidget()
        self.modelContentTab.setObjectName("modelContentTab")
        self.mainContent.addTab(self.modelContentTab, "")
        self.mainHLayout.addWidget(self.mainContent)
        self.verticalLayout.addLayout(self.mainHLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.mainContent.setCurrentIndex(0)
        self.domContent.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.domButton.setText(_translate("MainWindow", "DOM质检模块"))
        self.demButton.setText(_translate("MainWindow", "DEM质检模块"))
        self.stdataButton.setText(_translate("MainWindow", "时空专题数据质检模块"))
        self.modelButton.setText(_translate("MainWindow", "3D模型质检模块"))
        self.domWBILabel.setText(_translate("MainWindow", "数据路径"))
        self.domWBIBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domWBParamsGBox.setTitle(_translate("MainWindow", "参数设置"))
        self.label.setText(_translate("MainWindow", "影像异常值设置"))
        self.label_2.setText(_translate("MainWindow", "近似异常值距离"))
        self.label_3.setText(_translate("MainWindow", "非异常值容忍数"))
        self.domWBOLabel.setText(_translate("MainWindow", "输出路径"))
        self.domWBOBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domWBReportButton.setText(_translate("MainWindow", "导出质检报告"))
        self.domWBLogButton.setText(_translate("MainWindow", "打开日志目录"))
        self.domWBStartButton.setText(_translate("MainWindow", "开始检查"))
        self.domContent.setTabText(self.domContent.indexOf(self.domWBTab), _translate("MainWindow", "异常值检查"))
        self.domCILabel.setText(_translate("MainWindow", "索引数据路径"))
        self.domCIBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domCADLabel.setText(_translate("MainWindow", "行政区划路径"))
        self.domCADBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domCParamsGBox.setTitle(_translate("MainWindow", "参数设置"))
        self.label_6.setText(_translate("MainWindow", "市级行政区图层"))
        self.label_5.setText(_translate("MainWindow", "县级行政区图层"))
        self.domCOLabel.setText(_translate("MainWindow", "输出路径"))
        self.domCOBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domCReportButton.setText(_translate("MainWindow", "导出质检报告"))
        self.domCLogButton.setText(_translate("MainWindow", "打开日志目录"))
        self.domCStartButton.setText(_translate("MainWindow", "开始检查"))
        self.domContent.setTabText(self.domContent.indexOf(self.domCoverTab), _translate("MainWindow", "覆盖范围检查"))
        self.domFormatILabel.setText(_translate("MainWindow", "数据路径"))
        self.domFormatIBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domFormatParamsGBox.setTitle(_translate("MainWindow", "分辨率与坐标系参数"))
        self.domFormatPSettingButton.setText(_translate("MainWindow", "参数设置"))
        self.domFormatPResetButton.setText(_translate("MainWindow", "重置"))
        self.domFormatReportButton.setText(_translate("MainWindow", "导出质检报告"))
        self.domFormatLogButton.setText(_translate("MainWindow", "打开日志目录"))
        self.domFormatStartButton.setText(_translate("MainWindow", "开始检查"))
        self.domContent.setTabText(self.domContent.indexOf(self.domFormatTab), _translate("MainWindow", "分辨率与坐标系检查"))
        self.domMatchIndexLabel.setText(_translate("MainWindow", "索引路径"))
        self.domMatchIndexBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domMatchReportButton.setText(_translate("MainWindow", "导出质检报告"))
        self.domMatchLogButton.setText(_translate("MainWindow", "打开日志目录"))
        self.domMatchStartButton.setText(_translate("MainWindow", "开始检查"))
        self.domContent.setTabText(self.domContent.indexOf(self.domMatchTab), _translate("MainWindow", "影像与索引匹配检查"))
        self.mainContent.setTabText(self.mainContent.indexOf(self.domContentTab), _translate("MainWindow", "DOM"))
        self.mainContent.setTabText(self.mainContent.indexOf(self.demContentTab), _translate("MainWindow", "DEM"))
        self.mainContent.setTabText(self.mainContent.indexOf(self.stdataContentTab), _translate("MainWindow", "STD"))
        self.mainContent.setTabText(self.mainContent.indexOf(self.modelContentTab), _translate("MainWindow", "3D"))

