# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(5000, 5000))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainHLayout = QtWidgets.QHBoxLayout()
        self.mainHLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.mainHLayout.setContentsMargins(5, 5, 5, 5)
        self.mainHLayout.setSpacing(5)
        self.mainHLayout.setObjectName("mainHLayout")
        self.modelScrollArea = QtWidgets.QScrollArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelScrollArea.sizePolicy().hasHeightForWidth())
        self.modelScrollArea.setSizePolicy(sizePolicy)
        self.modelScrollArea.setMinimumSize(QtCore.QSize(210, 0))
        self.modelScrollArea.setMaximumSize(QtCore.QSize(210, 16777215))
        self.modelScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.modelScrollArea.setWidgetResizable(True)
        self.modelScrollArea.setObjectName("modelScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 191, 521))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.modelVerticalLayout = QtWidgets.QVBoxLayout()
        self.modelVerticalLayout.setSpacing(2)
        self.modelVerticalLayout.setObjectName("modelVerticalLayout")
        self.domButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.domButton.setMinimumSize(QtCore.QSize(0, 80))
        self.domButton.setMaximumSize(QtCore.QSize(16777215, 80))
        self.domButton.setObjectName("domButton")
        self.modelVerticalLayout.addWidget(self.domButton)
        self.demButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.demButton.setMinimumSize(QtCore.QSize(0, 80))
        self.demButton.setMaximumSize(QtCore.QSize(16777215, 80))
        self.demButton.setObjectName("demButton")
        self.modelVerticalLayout.addWidget(self.demButton)
        self.stdataButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.stdataButton.setMinimumSize(QtCore.QSize(0, 80))
        self.stdataButton.setMaximumSize(QtCore.QSize(16777215, 80))
        self.stdataButton.setObjectName("stdataButton")
        self.modelVerticalLayout.addWidget(self.stdataButton)
        self.modelButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.modelButton.setMinimumSize(QtCore.QSize(0, 80))
        self.modelButton.setMaximumSize(QtCore.QSize(16777215, 80))
        self.modelButton.setObjectName("modelButton")
        self.modelVerticalLayout.addWidget(self.modelButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.modelVerticalLayout.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.modelVerticalLayout)
        self.modelScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainHLayout.addWidget(self.modelScrollArea)
        self.mainContent = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainContent.sizePolicy().hasHeightForWidth())
        self.mainContent.setSizePolicy(sizePolicy)
        self.mainContent.setTabBarAutoHide(False)
        self.mainContent.setObjectName("mainContent")
        self.domContentTab = QtWidgets.QWidget()
        self.domContentTab.setObjectName("domContentTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.domContentTab)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.domVLayout = QtWidgets.QVBoxLayout()
        self.domVLayout.setContentsMargins(5, 5, 5, 5)
        self.domVLayout.setSpacing(5)
        self.domVLayout.setObjectName("domVLayout")
        self.domContent = QtWidgets.QTabWidget(self.domContentTab)
        self.domContent.setObjectName("domContent")
        self.domWBTab = QtWidgets.QWidget()
        self.domWBTab.setObjectName("domWBTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.domWBTab)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.domWBVLayout = QtWidgets.QVBoxLayout()
        self.domWBVLayout.setContentsMargins(5, 5, 5, 5)
        self.domWBVLayout.setSpacing(5)
        self.domWBVLayout.setObjectName("domWBVLayout")
        self.domWBParamsVLayout = QtWidgets.QVBoxLayout()
        self.domWBParamsVLayout.setContentsMargins(5, 5, 5, 5)
        self.domWBParamsVLayout.setSpacing(5)
        self.domWBParamsVLayout.setObjectName("domWBParamsVLayout")
        self.domWBParamsIGLayout = QtWidgets.QGridLayout()
        self.domWBParamsIGLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.domWBParamsIGLayout.setContentsMargins(5, 5, 5, 5)
        self.domWBParamsIGLayout.setSpacing(5)
        self.domWBParamsIGLayout.setObjectName("domWBParamsIGLayout")
        self.domWBILabel = QtWidgets.QLabel(self.domWBTab)
        self.domWBILabel.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBILabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBILabel.setObjectName("domWBILabel")
        self.domWBParamsIGLayout.addWidget(self.domWBILabel, 0, 0, 1, 1)
        self.domWBIBrowerButton = QtWidgets.QPushButton(self.domWBTab)
        self.domWBIBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBIBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBIBrowerButton.setObjectName("domWBIBrowerButton")
        self.domWBParamsIGLayout.addWidget(self.domWBIBrowerButton, 0, 2, 1, 1)
        self.domWBILineEdit = QtWidgets.QLineEdit(self.domWBTab)
        self.domWBILineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBILineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBILineEdit.setObjectName("domWBILineEdit")
        self.domWBParamsIGLayout.addWidget(self.domWBILineEdit, 0, 1, 1, 1)
        self.domWBParamsVLayout.addLayout(self.domWBParamsIGLayout)
        self.domWBParamsGBox = QtWidgets.QGroupBox(self.domWBTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domWBParamsGBox.sizePolicy().hasHeightForWidth())
        self.domWBParamsGBox.setSizePolicy(sizePolicy)
        self.domWBParamsGBox.setMinimumSize(QtCore.QSize(0, 80))
        self.domWBParamsGBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.domWBParamsGBox.setObjectName("domWBParamsGBox")
        self.spinBox = QtWidgets.QSpinBox(self.domWBParamsGBox)
        self.spinBox.setGeometry(QtCore.QRect(120, 30, 81, 21))
        self.spinBox.setMaximum(255)
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.domWBParamsGBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 91, 16))
        self.label.setObjectName("label")
        self.domWBParamsVLayout.addWidget(self.domWBParamsGBox)
        self.domWBPraramsOGLayout = QtWidgets.QGridLayout()
        self.domWBPraramsOGLayout.setContentsMargins(5, 5, 5, 5)
        self.domWBPraramsOGLayout.setSpacing(5)
        self.domWBPraramsOGLayout.setObjectName("domWBPraramsOGLayout")
        self.domWBOLabel = QtWidgets.QLabel(self.domWBTab)
        self.domWBOLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBOLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBOLabel.setObjectName("domWBOLabel")
        self.domWBPraramsOGLayout.addWidget(self.domWBOLabel, 0, 0, 1, 1)
        self.domWBOLineEdit = QtWidgets.QLineEdit(self.domWBTab)
        self.domWBOLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBOLineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBOLineEdit.setObjectName("domWBOLineEdit")
        self.domWBPraramsOGLayout.addWidget(self.domWBOLineEdit, 0, 1, 1, 1)
        self.domWBOBrowerButton = QtWidgets.QPushButton(self.domWBTab)
        self.domWBOBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domWBOBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domWBOBrowerButton.setObjectName("domWBOBrowerButton")
        self.domWBPraramsOGLayout.addWidget(self.domWBOBrowerButton, 0, 2, 1, 1)
        self.domWBParamsVLayout.addLayout(self.domWBPraramsOGLayout)
        self.line = QtWidgets.QFrame(self.domWBTab)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.domWBParamsVLayout.addWidget(self.line)
        self.domWBOpHLayout = QtWidgets.QHBoxLayout()
        self.domWBOpHLayout.setContentsMargins(5, 5, 5, 5)
        self.domWBOpHLayout.setSpacing(5)
        self.domWBOpHLayout.setObjectName("domWBOpHLayout")
        self.domWBReportButton = QtWidgets.QPushButton(self.domWBTab)
        self.domWBReportButton.setObjectName("domWBReportButton")
        self.domWBOpHLayout.addWidget(self.domWBReportButton)
        self.domWBLogButton = QtWidgets.QPushButton(self.domWBTab)
        self.domWBLogButton.setObjectName("domWBLogButton")
        self.domWBOpHLayout.addWidget(self.domWBLogButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.domWBOpHLayout.addItem(spacerItem1)
        self.domWBStartButton = QtWidgets.QPushButton(self.domWBTab)
        self.domWBStartButton.setObjectName("domWBStartButton")
        self.domWBOpHLayout.addWidget(self.domWBStartButton)
        self.domWBParamsVLayout.addLayout(self.domWBOpHLayout)
        self.domWBVLayout.addLayout(self.domWBParamsVLayout)
        self.domTableView = QtWidgets.QTableView(self.domWBTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domTableView.sizePolicy().hasHeightForWidth())
        self.domTableView.setSizePolicy(sizePolicy)
        self.domTableView.setObjectName("domTableView")
        self.domWBVLayout.addWidget(self.domTableView)
        self.verticalLayout_3.addLayout(self.domWBVLayout)

        self.domContent.addTab(self.domWBTab, "")
        self.domCoverTab = QtWidgets.QWidget()
        self.domCoverTab.setObjectName("domCoverTab")
        self.domContent.addTab(self.domCoverTab, "")

        self.domFormatTab = QtWidgets.QWidget()
        self.domFormatTab.setObjectName("domFormatTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.domFormatTab)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.domFormatVLayout = QtWidgets.QVBoxLayout()
        self.domFormatVLayout.setContentsMargins(5, 5, 5, 5)
        self.domFormatVLayout.setSpacing(5)
        self.domFormatVLayout.setObjectName("domFormatVLayout")
        self.domFormatParamsVLayout = QtWidgets.QVBoxLayout()
        self.domFormatParamsVLayout.setContentsMargins(5, 5, 5, 5)
        self.domFormatParamsVLayout.setSpacing(5)
        self.domFormatParamsVLayout.setObjectName("domFormatParamsVLayout")
        self.domFormatParamsIGLayout = QtWidgets.QGridLayout()
        self.domFormatParamsIGLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.domFormatParamsIGLayout.setContentsMargins(5, 5, 5, 5)
        self.domFormatParamsIGLayout.setSpacing(5)
        self.domFormatParamsIGLayout.setObjectName("domFormatParamsIGLayout")
        self.domFormatILabel = QtWidgets.QLabel(self.domFormatTab)
        self.domFormatILabel.setMinimumSize(QtCore.QSize(0, 24))
        self.domFormatILabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domFormatILabel.setObjectName("domFormatILabel")
        self.domFormatParamsIGLayout.addWidget(self.domFormatILabel, 0, 0, 1, 1)
        self.domFormatIBrowerButton = QtWidgets.QPushButton(self.domFormatTab)
        self.domFormatIBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domFormatIBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domFormatIBrowerButton.setObjectName("domFormatIBrowerButton")
        self.domFormatParamsIGLayout.addWidget(self.domFormatIBrowerButton, 0, 2, 1, 1)
        self.domFormatILineEdit = QtWidgets.QLineEdit(self.domFormatTab)
        self.domFormatILineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domFormatILineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domFormatILineEdit.setObjectName("domFormatILineEdit")
        self.domFormatParamsIGLayout.addWidget(self.domFormatILineEdit, 0, 1, 1, 1)
        self.domFormatParamsVLayout.addLayout(self.domFormatParamsIGLayout)
        self.domFormatParamsGBox = QtWidgets.QGroupBox(self.domFormatTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domFormatParamsGBox.sizePolicy().hasHeightForWidth())
        self.domFormatParamsGBox.setSizePolicy(sizePolicy)
        self.domFormatParamsGBox.setMinimumSize(QtCore.QSize(0, 80))
        self.domFormatParamsGBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.domFormatParamsGBox.setObjectName("domFormatParamsGBox")
        self.gridLayout = QtWidgets.QGridLayout(self.domFormatParamsGBox)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.domFormatPButtonVLayout = QtWidgets.QVBoxLayout()
        self.domFormatPButtonVLayout.setContentsMargins(5, 5, 5, 5)
        self.domFormatPButtonVLayout.setSpacing(5)
        self.domFormatPButtonVLayout.setObjectName("domFormatPButtonVLayout")
        self.domFormatPSettingButton = QtWidgets.QPushButton(self.domFormatParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domFormatPSettingButton.sizePolicy().hasHeightForWidth())
        self.domFormatPSettingButton.setSizePolicy(sizePolicy)
        self.domFormatPSettingButton.setObjectName("domFormatPSettingButton")
        self.domFormatPButtonVLayout.addWidget(self.domFormatPSettingButton)
        self.domFormatPResetButton = QtWidgets.QPushButton(self.domFormatParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domFormatPResetButton.sizePolicy().hasHeightForWidth())
        self.domFormatPResetButton.setSizePolicy(sizePolicy)
        self.domFormatPResetButton.setObjectName("domFormatPResetButton")
        self.domFormatPButtonVLayout.addWidget(self.domFormatPResetButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.domFormatPButtonVLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.domFormatPButtonVLayout, 0, 1, 1, 1)
        self.domFormatListWidget = QtWidgets.QListWidget(self.domFormatParamsGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domFormatListWidget.sizePolicy().hasHeightForWidth())
        self.domFormatListWidget.setSizePolicy(sizePolicy)
        self.domFormatListWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.domFormatListWidget.setObjectName("domFormatListWidget")
        self.gridLayout.addWidget(self.domFormatListWidget, 0, 0, 1, 1)
        self.domFormatParamsVLayout.addWidget(self.domFormatParamsGBox)
        self.line_4 = QtWidgets.QFrame(self.domFormatTab)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.domFormatParamsVLayout.addWidget(self.line_4)
        self.domFormatOpHLayout = QtWidgets.QHBoxLayout()
        self.domFormatOpHLayout.setContentsMargins(5, 5, 5, 5)
        self.domFormatOpHLayout.setSpacing(5)
        self.domFormatOpHLayout.setObjectName("domFormatOpHLayout")
        self.domFormatReportButton = QtWidgets.QPushButton(self.domFormatTab)
        self.domFormatReportButton.setObjectName("domFormatReportButton")
        self.domFormatOpHLayout.addWidget(self.domFormatReportButton)
        self.domFormatLogButton = QtWidgets.QPushButton(self.domFormatTab)
        self.domFormatLogButton.setObjectName("domFormatLogButton")
        self.domFormatOpHLayout.addWidget(self.domFormatLogButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.domFormatOpHLayout.addItem(spacerItem3)
        self.domFormatStartButton = QtWidgets.QPushButton(self.domFormatTab)
        self.domFormatStartButton.setObjectName("domFormatStartButton")
        self.domFormatOpHLayout.addWidget(self.domFormatStartButton)
        self.domFormatParamsVLayout.addLayout(self.domFormatOpHLayout)
        self.domFormatVLayout.addLayout(self.domFormatParamsVLayout)
        self.domFormatTableWidget = QtWidgets.QTableWidget(self.domFormatTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domFormatTableWidget.sizePolicy().hasHeightForWidth())
        self.domFormatTableWidget.setSizePolicy(sizePolicy)
        self.domFormatTableWidget.setObjectName("domFormatTableWidget")
        self.domFormatTableWidget.setColumnCount(0)
        self.domFormatTableWidget.setRowCount(0)
        self.domFormatVLayout.addWidget(self.domFormatTableWidget)
        self.verticalLayout_6.addLayout(self.domFormatVLayout)
        self.domContent.addTab(self.domFormatTab, "")
        self.domMatchTab = QtWidgets.QWidget()
        self.domMatchTab.setObjectName("domMatchTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.domMatchTab)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.domMatchVLayout = QtWidgets.QVBoxLayout()
        self.domMatchVLayout.setContentsMargins(5, 5, 5, 5)
        self.domMatchVLayout.setSpacing(5)
        self.domMatchVLayout.setObjectName("domMatchVLayout")
        self.domMatchParamsVLayout = QtWidgets.QVBoxLayout()
        self.domMatchParamsVLayout.setContentsMargins(5, 5, 5, 5)
        self.domMatchParamsVLayout.setSpacing(5)
        self.domMatchParamsVLayout.setObjectName("domMatchParamsVLayout")
        self.domMatchParamsIGLayout = QtWidgets.QGridLayout()
        self.domMatchParamsIGLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.domMatchParamsIGLayout.setContentsMargins(5, 5, 5, 5)
        self.domMatchParamsIGLayout.setSpacing(5)
        self.domMatchParamsIGLayout.setObjectName("domMatchParamsIGLayout")
        self.domMatchIBrowerButton = QtWidgets.QPushButton(self.domMatchTab)
        self.domMatchIBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domMatchIBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domMatchIBrowerButton.setObjectName("domMatchIBrowerButton")
        self.domMatchParamsIGLayout.addWidget(self.domMatchIBrowerButton, 0, 2, 1, 1)
        self.domMatchILineEdit = QtWidgets.QLineEdit(self.domMatchTab)
        self.domMatchILineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domMatchILineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domMatchILineEdit.setObjectName("domMatchILineEdit")
        self.domMatchParamsIGLayout.addWidget(self.domMatchILineEdit, 0, 1, 1, 1)
        self.domMatchILabel = QtWidgets.QLabel(self.domMatchTab)
        self.domMatchILabel.setMinimumSize(QtCore.QSize(0, 24))
        self.domMatchILabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domMatchILabel.setObjectName("domMatchILabel")
        self.domMatchParamsIGLayout.addWidget(self.domMatchILabel, 0, 0, 1, 1)
        self.domMatchParamsVLayout.addLayout(self.domMatchParamsIGLayout)
        self.domMatchParamsIndexGLayout = QtWidgets.QGridLayout()
        self.domMatchParamsIndexGLayout.setContentsMargins(5, 5, 5, 5)
        self.domMatchParamsIndexGLayout.setSpacing(5)
        self.domMatchParamsIndexGLayout.setObjectName("domMatchParamsIndexGLayout")
        self.domMatchIndexLabel = QtWidgets.QLabel(self.domMatchTab)
        self.domMatchIndexLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.domMatchIndexLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domMatchIndexLabel.setObjectName("domMatchIndexLabel")
        self.domMatchParamsIndexGLayout.addWidget(self.domMatchIndexLabel, 0, 0, 1, 1)
        self.domMatchIndexBrowerButton = QtWidgets.QPushButton(self.domMatchTab)
        self.domMatchIndexBrowerButton.setMinimumSize(QtCore.QSize(0, 24))
        self.domMatchIndexBrowerButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domMatchIndexBrowerButton.setObjectName("domMatchIndexBrowerButton")
        self.domMatchParamsIndexGLayout.addWidget(self.domMatchIndexBrowerButton, 0, 2, 1, 1)
        self.domMatchIndexLineEdit = QtWidgets.QLineEdit(self.domMatchTab)
        self.domMatchIndexLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.domMatchIndexLineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.domMatchIndexLineEdit.setObjectName("domMatchIndexLineEdit")
        self.domMatchParamsIndexGLayout.addWidget(self.domMatchIndexLineEdit, 0, 1, 1, 1)
        self.domMatchParamsVLayout.addLayout(self.domMatchParamsIndexGLayout)
        self.line_6 = QtWidgets.QFrame(self.domMatchTab)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.domMatchParamsVLayout.addWidget(self.line_6)
        self.domMatchOpHLayout = QtWidgets.QHBoxLayout()
        self.domMatchOpHLayout.setContentsMargins(5, 5, 5, 5)
        self.domMatchOpHLayout.setSpacing(5)
        self.domMatchOpHLayout.setObjectName("domMatchOpHLayout")
        self.domMatchReportButton = QtWidgets.QPushButton(self.domMatchTab)
        self.domMatchReportButton.setObjectName("domMatchReportButton")
        self.domMatchOpHLayout.addWidget(self.domMatchReportButton)
        self.domMatchLogButton = QtWidgets.QPushButton(self.domMatchTab)
        self.domMatchLogButton.setObjectName("domMatchLogButton")
        self.domMatchOpHLayout.addWidget(self.domMatchLogButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.domMatchOpHLayout.addItem(spacerItem4)
        self.domMatchStartButton = QtWidgets.QPushButton(self.domMatchTab)
        self.domMatchStartButton.setObjectName("domMatchStartButton")
        self.domMatchOpHLayout.addWidget(self.domMatchStartButton)
        self.domMatchParamsVLayout.addLayout(self.domMatchOpHLayout)
        self.domMatchVLayout.addLayout(self.domMatchParamsVLayout)
        self.domMatchTableWidget = QtWidgets.QTableWidget(self.domMatchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domMatchTableWidget.sizePolicy().hasHeightForWidth())
        self.domMatchTableWidget.setSizePolicy(sizePolicy)
        self.domMatchTableWidget.setObjectName("domMatchTableWidget")
        self.domMatchTableWidget.setColumnCount(0)
        self.domMatchTableWidget.setRowCount(0)
        self.domMatchVLayout.addWidget(self.domMatchTableWidget)
        self.verticalLayout_7.addLayout(self.domMatchVLayout)
        self.domContent.addTab(self.domMatchTab, "")
        self.domVLayout.addWidget(self.domContent)
        self.verticalLayout_2.addLayout(self.domVLayout)
        self.mainContent.addTab(self.domContentTab, "")
        self.demContentTab = QtWidgets.QWidget()
        self.demContentTab.setObjectName("demContentTab")
        self.mainContent.addTab(self.demContentTab, "")
        self.stdataContentTab = QtWidgets.QWidget()
        self.stdataContentTab.setObjectName("stdataContentTab")
        self.mainContent.addTab(self.stdataContentTab, "")
        self.modelContentTab = QtWidgets.QWidget()
        self.modelContentTab.setObjectName("modelContentTab")
        self.mainContent.addTab(self.modelContentTab, "")
        self.mainHLayout.addWidget(self.mainContent)
        self.verticalLayout.addLayout(self.mainHLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.mainContent.setCurrentIndex(0)
        self.domContent.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.domButton.setText(_translate("MainWindow", "DOM质检模块"))
        self.demButton.setText(_translate("MainWindow", "DEM质检模块"))
        self.stdataButton.setText(_translate("MainWindow", "时空专题数据质检模块"))
        self.modelButton.setText(_translate("MainWindow", "3D模型质检模块"))
        self.domWBILabel.setText(_translate("MainWindow", "数据路径"))
        self.domWBIBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domWBParamsGBox.setTitle(_translate("MainWindow", "参数设置"))
        self.label.setText(_translate("MainWindow", "影像异常值设置"))
        self.domWBOLabel.setText(_translate("MainWindow", "输出路径"))
        self.domWBOBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domWBReportButton.setText(_translate("MainWindow", "导出质检报告"))
        self.domWBLogButton.setText(_translate("MainWindow", "打开日志目录"))
        self.domWBStartButton.setText(_translate("MainWindow", "开始检查"))
        self.domContent.setTabText(self.domContent.indexOf(self.domWBTab), _translate("MainWindow", "异常值检查"))
        self.domContent.setTabText(self.domContent.indexOf(self.domCoverTab), _translate("MainWindow", "覆盖范围检查"))
        self.domFormatILabel.setText(_translate("MainWindow", "数据路径"))
        self.domFormatIBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domFormatParamsGBox.setTitle(_translate("MainWindow", "分辨率与坐标系参数"))
        self.domFormatPSettingButton.setText(_translate("MainWindow", "参数设置"))
        self.domFormatPResetButton.setText(_translate("MainWindow", "重置"))
        self.domFormatReportButton.setText(_translate("MainWindow", "导出质检报告"))
        self.domFormatLogButton.setText(_translate("MainWindow", "打开日志目录"))
        self.domFormatStartButton.setText(_translate("MainWindow", "开始检查"))
        self.domContent.setTabText(self.domContent.indexOf(self.domFormatTab), _translate("MainWindow", "分辨率与坐标系检查"))
        self.domMatchIBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domMatchILabel.setText(_translate("MainWindow", "数据路径"))
        self.domMatchIndexLabel.setText(_translate("MainWindow", "索引路径"))
        self.domMatchIndexBrowerButton.setText(_translate("MainWindow", "浏览..."))
        self.domMatchReportButton.setText(_translate("MainWindow", "导出质检报告"))
        self.domMatchLogButton.setText(_translate("MainWindow", "打开日志目录"))
        self.domMatchStartButton.setText(_translate("MainWindow", "开始检查"))
        self.domContent.setTabText(self.domContent.indexOf(self.domMatchTab), _translate("MainWindow", "影像与索引匹配检查"))
        self.mainContent.setTabText(self.mainContent.indexOf(self.domContentTab), _translate("MainWindow", "DOM"))
        self.mainContent.setTabText(self.mainContent.indexOf(self.demContentTab), _translate("MainWindow", "DEM"))
        self.mainContent.setTabText(self.mainContent.indexOf(self.stdataContentTab), _translate("MainWindow", "STD"))
        self.mainContent.setTabText(self.mainContent.indexOf(self.modelContentTab), _translate("MainWindow", "3D"))

